# Generated by Django 5.0.6 on 2024-06-17 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('files', models.ManyToManyField(blank=True, to='apiService.file')),
                ('folders', models.ManyToManyField(blank=True, to='apiService.folder')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiService.folder')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiService.folder'),
        ),
    ]
